function [BW,maskedImage] = justCarWhite(X)
%segmentImage Segment image using auto-generated code from Image Segmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the Image Segmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 03-Feb-2025
%----------------------------------------------------

%X = rgb2gray(X);
%X = imgaussfilt(X);
F = fspecial("average",6);
X = imfilter(X, F);

% Adjust data to span data range.
X = imadjust(X);

% Threshold image with manual threshold
BW = im2gray(X) > 2.524500e+02;

% Close mask with disk
radius = 11;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imclose(BW, se);

% Draw ROIs

xPos = [308.8741 318.1660 508.6494 544.6555 348.3646];
yPos = [505.1435 459.8475 420.3587 480.7534 518.5000];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW & ~addedRegion;



% Threshold image with manual threshold
BW2 = im2gray(X) > 5.610000e+01;

% Dilate mask with disk
radius = 2;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW2 = imdilate(BW2, se);

% Dilate mask with disk
radius = 3;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW2 = imdilate(BW2, se);

BW2 = ~BW2;
%BW2 = bwpropfilt(BW2,'Area',[3500, 24000]);
%properties2 = regionprops("table", BW, {'Area'});
%frame = inserShape(img, "Rectangle", properties2.BoundingBox, "color","red","LineWidth",5);

BW = BW | BW2;


% Draw ROIs

xPos = [549.3014 588.7919 901.2312 912.8460];
yPos = [4.5650 19.6637 15.0179 2.2422];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW & ~addedRegion;

% Draw ROIs

xPos = [462.1901 483.0968 480.7738 458.7056];
yPos = [339.0583 332.0897 454.0404 454.0404];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW & ~addedRegion;

xPos = [1153.2733 965.1128 902.3927 1152.1118];
yPos = [284.4709 332.0897 514.4350 516.7578];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW & ~addedRegion;

xPos = [11.5341 82.3847 126.5211 11.5341];
yPos = [148.5830 131.1614 90.5112 61.4753];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW & ~addedRegion;

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

